console.log(Number(null))
console.log(Number(undefined))
console.log(Boolean(''))
console.log(Boolean('123'))
console.log(Boolean(null))
console.log(Boolean(NaN))
console.log(String(null))
console.log(String(undefined))
console.log(parseInt(undefined));
console.log(parseInt(false))
console.log(parseInt(" 0.123"))
console.log(parseInt('hzong'))
console.log(parseFloat(0.023))
console.log(parseFloat(null))
console.log(parseFloat(" 5454"));
console.log(toString(null))
console.log(toString(undefined))
console.log(toString(0))
console.log(toString(""))
console.log(toString("123"))
console.log(toString(true))
console.log(toString())
